Added sum function
js-tasks-ru/js-20200821-3_artemcx pull request #1
Opened 2020-08-23 16:21 UTC by ArteMCX

Added sum function to index.js

2020-08-23 16:28 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Первая задача
+ should return sum of numbers
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-08-25 08:31 UTC, dosandk commented on 01-intro/1-sum/index.js
> +	return Number(m) + Number(n);
В данной задаче нет необходимости приводить аргументы к числу, чтобы в этом убедиться - посмотрите файл с тестами.
Приведение нужно убрать

2020-08-25 08:31 UTC, dosandk requested changes
необходимо внести правки согласно коментам

2020-08-25 09:04 UTC, jsru commented
@dosandk ping :)

2020-08-25 09:26 UTC, dosandk approved these changes
good 👍

2020-08-25 09:26 UTC, merged